stof_doctrine_extensions:
    default_locale: %default_locale%
    translation_fallback: true
    orm:
        default:
            translatable:     true
            timestampable:    true
            tree:             true
