parameters:
    orocrm_sales.opportunity.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityType
    orocrm_sales.opportunity.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityApiType
    orocrm_sales.opportunity.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\OpportunityHandler

    orocrm_sales.lead.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadType
    orocrm_sales.lead.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadApiType
    orocrm_sales.lead.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadHandler

    orocrm_sales.lead_address.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadAddressType

services:
    orocrm_sales.opportunity.form.type:
        class: %orocrm_sales.opportunity.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity }

    orocrm_sales.opportunity.form.type.api:
        class: %orocrm_sales.opportunity.form.type.api.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity_api }

    orocrm_sales.opportunity.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_opportunity_form"
            - "orocrm_sales_opportunity"

    orocrm_sales.opportunity.form.api:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "opportunity"
            - "orocrm_sales_opportunity_api"

    orocrm_sales.opportunity.form.handler:
        class: %orocrm_sales.opportunity.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.opportunity.form
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.opportunity.form.handler.api:
        class: %orocrm_sales.opportunity.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.opportunity.form.api
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.form.type:
        class: %orocrm_sales.lead.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead }

    orocrm_sales.lead.form.type.api:
        class: %orocrm_sales.lead.form.type.api.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_api }

    orocrm_sales.lead.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_lead_form"
            - "orocrm_sales_lead"

    orocrm_sales.lead.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "lead"
            - "orocrm_sales_lead_api"

    orocrm_sales.lead.form.handler:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.lead.form
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.form.handler.api:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.lead.form.api
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.lead_address.form.type:
        class: %orocrm_sales.lead_address.form.type.class%
        arguments:
            - @oro_address.form.listener.address
        tags:
            - { name: form.type, alias: orocrm_lead_address }
