parameters:
    orocrm_sales.opportunity.class: OroCRM\Bundle\SalesBundle\Entity\Opportunity
    orocrm_sales.opportunity.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    orocrm_sales.lead.entity.class: OroCRM\Bundle\SalesBundle\Entity\Lead
    orocrm_sales.lead.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    orocrm_sales.opportunity.manager.api:
        class: %orocrm_sales.opportunity.manager.api.class%
        arguments:
            - %orocrm_sales.opportunity.class%
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.manager.api:
        class: %orocrm_sales.lead.manager.api.class%
        arguments:
            - %orocrm_sales.lead.entity.class%
            - @doctrine.orm.entity_manager
